// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBeYoTh-h9tn_JH__lrJ6HYv0ecvX0JFs',
    appId: '1:153746750887:android:03a4e7c592dc60696cca82',
    messagingSenderId: '153746750887',
    projectId: 'happyelders-customer',
    databaseURL:
        'https://happyelders-customer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyelders-customer.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJqDvDrYYxOCU11j7W2kSTtDFaZw-TGE0',
    appId: '1:153746750887:ios:de6eec1dcc06a2bb6cca82',
    messagingSenderId: '153746750887',
    projectId: 'happyelders-customer',
    databaseURL:
        'https://happyelders-customer-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'happyelders-customer.appspot.com',
    iosClientId:
        '153746750887-matiskfqp2h0sg5h41p0ei445bqq9392.apps.googleusercontent.com',
    iosBundleId: 'com.example.olive',
  );
}
